import React from 'react'

export default function Terms() {
    return (
        <div className='flex flex-col sm:pl-20 sm:pr-20 pl-5 pr-5 lg:pl-60 lg:pr-60 md:pl-40 md:pr-40  pt-10 pb-10 bg-gray-100'>
            <div className='bg-white px-5 py-2 border rounded-md'>
                <h1 className='flex pt-5 font-extrabold text-2xl'>Terms of Service</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>Welcome to Featherr, a cutting-edge application driven by Generative Artificial Intelligence (AI).</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>Please read this terms of service agreement before using our application. By using our application, you agree to the following terms:</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>1. All answers and responses generated by the AI assistant are not guaranteed to be true or accurate. The responses are driven by generative AI and are based on pre-existing data and algorithms.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>2. The AI assistant is not a substitute for professional advice, diagnosis, or treatment. Users are solely responsible for validating any information provided by the AI assistant.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>3. The AI assistant may be updated by us from time to time without notice. However, we do not guarantee that the AI assistant will be free from errors or interruptions.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>4. You may use the AI assistant for lawful purposes only. You may not use the AI assistant to transmit any content that is unlawful, harmful, threatening, defamatory, obscene, or otherwise objectionable.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>5. By using the AI assistant, you agree that we may collect and analyze data and information about how you use the application. We will use this information to improve our services and provide better customer support.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>6. Your access to the AI assistant may be terminated at any time for any reason.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900'>7. This agreement is governed by the laws of the United States of America and any dispute will be resolved in a court of law.</h1>
                <h1 className='flex pt-5 font-bold text-gray-900 pb-5'>By using Featherr, you acknowledge and agree to these terms of service.</h1>
            </div>
            <div className='absolute top-0 left-0 w-full h-screen bg-gray-100 z-[-1]'></div>
        </div>
    )
}
